from dataclasses import make_dataclass
from typing import Dict, List

NAMES: List[str] = [
    # ----------TGFbeta1 activation
    'kf_1_TGFbeta',
    'Kmf_1_TGFbeta',
    'k_on_FMOD',
    'k_off_FMOD',
    'Rec_act',	
    'pRec_debind',
    # ----------TGFbeta pathway
	'S2tot',
	'S3tot',
	'S4tot',
	'kf_2_TGFbeta',
	'Kmf_2_TGFbeta',
	'k_inhibit_TGF',
	'S_dephosphos',
	'S_dephos',
	'kf_3_TGFbeta',
	'Kmf_3_TGFbeta',
	'k_on_ppS2_ppS3',
	'k_on_ppS2_ppS3_S4',
	'k_off_ppS2_ppS3_S4',
	# ----------SMAD7
	'prod_mS7',
	'n1_TGF',
	'Km_1_TGF',
	'mS7_turn',
	'prod_S7',
	# ----------cFOS
	'prod_mcFOS',
	'n2_TGF',
	'Km_2_TGF',
	'mcFOS_turn',
	'prod_cFOS',
	'k_on_ppS2_ppS3_S4_cFOS',
	'k_off_ppS2_ppS3_S4_cFOS',
	# ----------THBS1
	'prod_mTHBS1',
	'n4_TGF',
	'Km_4_TGF',
	'THBS1_turn',
	'prod_THBS1',
	# ----------Weight genes
    'w_THBS1',
    'w_TGFBR1',
    'w_TGFBR2',
    'w_SMAD7',
    'w_cFOS',
	# ----------degrad
    'degrad_cFOS', 
    # Birtwistle et al., MSB (2007)
    'VmaxPY',
    'KmPY',
    'kdeg',
    'kf47',
    'Vmaxr47',
    'Kmf47',
    'Kmr47',
    'kf48',
    'Kmf48',
    'Kmr48',
    'PTEN',
    'kf49',
    'kr49',
    'Kmf49',
    'Kmr49',
    'Kmr49b',
    'kr49b',
    'kf51',
    'Vmaxr51',
    'Kmf51',
    'Kmrb51',
    'kf52',
    'Vmaxr52',
    'Kmf52',
    'Kmr52',
    'kf54',
    'Vmaxr54',
    'Kmf54',
    'Kmr54',
    'kf55',
    'Vmaxr55',
    'Kmf55',
    'Kmr55',
    'kf38',
    'kf39',
    'kf50',
    'a98',
    'b98',
    'koff46',
    'EGF_off',
    'koff4',
    'koff16',
    'koff17',
    'koff18',
    'koff40',
    'koff41',
    'koff42',
    'koff43',
    'koff44',
    'koff45',
    'koff57',
    'koff58',
    'koff59',
    'koff60',
    'kPTP10',
    'koff73',
    'kPTP38',
    'kPTP39',
    'koff88',
    'kPTP50',
    'kf81',
    'Vmaxr81',
    'Kmf81',
    'Kmr81',
    'kf84',
    'Vmaxr84',
    'Kmf84',
    'Kmr84',
    'kcon49',
    'kon1',
    'kon86',
    'kon4',
    'kf10',
    'kon16',
    'kon17',
    'kon18',
    'kon73',
    'kon40',
    'kon41',
    'kon42',
    'kon43',
    'kon44',
    'kon45',
    'kon88',
    'kon46',
    'kon57',
    'kon58',
    'kon59',
    'kon60',
    # Nakakuki et al., Cell (2010)
    'V1',
    'Km1',
    'V2',
    'Km2',
    'V3',
    'Km3',
    'V4',
    'Km4',
    'V5',
    'Km5',
    'V6',
    'Km6',
    'KimERK',
    'KexERK',
    'KimpERK',
    'KexpERK',
    'KimppERK',
    'KexppERK',
    'Vn',
    'Vc',
    # ----------PI3K-Akt pathway
    'act_PI3K',
    'inact_PI3K',
    # ----------VEGF pathway(downstream of ERK)
    'kf_16_vegf',
    'Kmf_16_vegf',
    'kr_17_vegf',
    'Kmr_17_vegf',
    'prod_mFMOD',
    'Km_18_vegf',
    'n1_vegf',
    'degrad_mFMOD',
    'prod_FMOD',
    # weight for initial value
    'w_VEGFR1',
    'w_VEGFR2',
    #GRB2
    'w_G',
    #'w_S',
    'w_SHC1',
    'w_SHC2',
    'w_SHC3',
    'w_SHC4',
    #'w_I',PI3K
    'w_PIK3CA',
    'w_PIK3CB',
    'w_PIK3CD',
    'w_PIK3CG',
    # PTEN
    'w_PTEN',
    #'w_R',
    'w_RASA1',
    'w_RASA2',
    'w_RASA3',
    #'w_O',
    'w_SOS1',
    'w_SOS2',
    # w_A, GAB1
    'w_A',
    #'w_Akt',
    'w_AKT1',
    'w_AKT2',
    #'w_RsD',
    'w_HRAS',
    'w_KRAS',
    'w_NRAS',
    #'w_Raf',
    'w_ARAF',
    'w_BRAF',
    'w_RAF1',
    #MEK
    'w_MAP2K1',
    'w_MAP2K2',
    #PTPN1
    'w_T',
    #ERK
    'w_MAPK1',
    'w_MAPK3',
    'w_FMOD',
]

NUM: int = len(NAMES)

Parameters = make_dataclass(
    cls_name="Parameters",
    fields=[(name, int) for name in NAMES],
    namespace={"NAMES": NAMES, "NUM": NUM},
    frozen=True,
)

name2idx: Dict[str, int] = {k: v for v, k in enumerate(NAMES)}

C = Parameters(**name2idx)

del name2idx
