#!/usr/bin/bash

echo "####################################################################"
echo "#              Dataset for Dermal fibroblast senescence            #"
echo "#              Analysis of Motif enrichment (Gained ATAC-seq peaks)#"
echo "#              Data prepared by Haga et al.                        #"
echo "####################################################################"

#Concatenated using “cat” command ATAC-seq gained peaks
#Use bed files generated by 5_Gain_peaks_ATAC_ChIP_seq.R
cat ATAC_PDL24_PDL36_gain.bed ATAC_PDL24_PDL47_gain.bed ATAC_PDL36_PDL47_gain.bed > tmp1_gain.bed
sortBed -i tmp1_gain.bed > tmp2_gain.bed
mergeBed -i tmp2_gain.bed > ATAC_output_gain.bed
rm -rf tmp1_gain.bed tmp2_gain.bed

#HOMER ver4.11
#Use ATAC-seq gained peaks
echo "Perform HOMER (ver. 4.11) findMotifsGenome.pl" 
findMotifsGenome.pl ATAC_output_gain.bed hg38 HOMER_Motifs -size given -p 8

